FROM rust:1.79-slim AS builder
WORKDIR /app
COPY remote-core/ .
RUN cargo build –release
FROM debian:bookworm-slim
WORKDIR /app
COPY –from=builder /app/target/release/vgorode-remote-core .
EXPOSE 9000
CMD [”./vgorode-remote-core”]
